/*
 * Copyright 2017 BarelyAliveMau5.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ui;

import gerenciador.Controle;
import gerenciador.Perfil;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.JOptionPane;

/**
 *
 * @author BarelyAliveMau5
 */
public class frmNovoPerfil extends javax.swing.JFrame {

    private final Controle ctl;
    private File imgDigital;
    private File imgPerfil;
    /**
     * Creates new form frmNovoPerfil
     * @param ctl controlador
     */
    public frmNovoPerfil(Controle ctl) {
        initComponents();
        this.ctl = ctl;
        this.setLocationRelativeTo(null);  // centralizar janela
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lblID = new javax.swing.JLabel();
        _lblNome = new javax.swing.JLabel();
        _lblPosicao = new javax.swing.JLabel();
        pnFoto = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cbPosicao = new javax.swing.JComboBox(Perfil.Posicoes.values());
        spID = new javax.swing.JSpinner();
        btnCarregarDigital = new javax.swing.JButton();
        btnCriar = new javax.swing.JButton();
        _lblFoto = new javax.swing.JLabel();
        pnDigital = new javax.swing.JPanel();
        lblDigital = new javax.swing.JLabel();
        _lblDigitais = new javax.swing.JLabel();
        _btnApagarDigital = new javax.swing.JButton();
        btnCarregarFoto = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        _btnApagar = new javax.swing.JButton();
        _lblDPI = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criar perfil");
        setResizable(false);

        _lblID.setText("ID:");

        _lblNome.setText("Nome:");

        _lblPosicao.setText("Posição:");

        pnFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnFoto.setLayout(new java.awt.GridLayout(1, 0));

        lblFoto.setText(" ");
        pnFoto.add(lblFoto);

        txtNome.setText("NOME");

        btnCarregarDigital.setText("Carregar");
        btnCarregarDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarDigitalActionPerformed(evt);
            }
        });

        btnCriar.setText("Criar perfil");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        _lblFoto.setText("Foto:");

        pnDigital.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnDigital.setLayout(new java.awt.GridLayout(1, 0));

        lblDigital.setText(" ");
        pnDigital.add(lblDigital);

        _lblDigitais.setText("Digitais:");

        _btnApagarDigital.setText("Apagar");
        _btnApagarDigital.setEnabled(false);

        btnCarregarFoto.setText("Carregar");
        btnCarregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarFotoActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setEnabled(false);

        _btnApagar.setText("Apagar perfil");
        _btnApagar.setEnabled(false);

        _lblDPI.setText("DPI (0 = ignorado):");

        jTextField1.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(_lblDigitais)
                                        .addGap(83, 83, 83)
                                        .addComponent(_lblDPI)
                                        .addGap(0, 79, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(cbPosicao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                                        .addGap(9, 9, 9)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCarregarFoto)
                                    .addComponent(pnFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCarregarDigital)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_btnApagarDigital)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_btnApagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCriar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_lblNome)
                            .addComponent(_lblID)
                            .addComponent(_lblPosicao)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_lblFoto)
                        .addGap(131, 131, 131))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_lblID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_lblPosicao)
                            .addComponent(cbPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_lblDigitais)
                            .addComponent(_lblDPI))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_lblFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarregarFoto)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregarDigital)
                    .addComponent(_btnApagarDigital)
                    .addComponent(btnCriar)
                    .addComponent(_btnApagar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        int id_novo_usr = 0;
        try {
            id_novo_usr = new Controle() {
                public int criarUsuario() throws IOException {
                    Perfil.Posicoes pos = Perfil.Posicoes.valueOf(cbPosicao.getSelectedItem().toString());
                    byte[] img = null;
                    if (imgPerfil != null)
                        img = Files.readAllBytes(imgPerfil.toPath());
                    return super.criarUsuario(imgDigital, null, txtNome.getText(), pos, img);
                }
            }.criarUsuario();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro na leitura da imagem. " + ex.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
        if (id_novo_usr > 0) 
            JOptionPane.showMessageDialog(null, "Usuario criado. ID = " + String.valueOf(id_novo_usr),
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        else {
            if (id_novo_usr < 0) 
                JOptionPane.showMessageDialog(null, "Digital já cadastrada.", "Erro" ,
                    JOptionPane.ERROR_MESSAGE);
            else
                JOptionPane.showMessageDialog(null, "Ocorreu algum erro na escrita dos dados.", "Erro" ,
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnCarregarDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarDigitalActionPerformed
        imgDigital = frmAutenticar.carregarImagem(lblDigital);
    }//GEN-LAST:event_btnCarregarDigitalActionPerformed

    private void btnCarregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarFotoActionPerformed
        imgPerfil = frmAutenticar.carregarImagem(lblFoto);
    }//GEN-LAST:event_btnCarregarFotoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnApagar;
    private javax.swing.JButton _btnApagarDigital;
    private javax.swing.JLabel _lblDPI;
    private javax.swing.JLabel _lblDigitais;
    private javax.swing.JLabel _lblFoto;
    private javax.swing.JLabel _lblID;
    private javax.swing.JLabel _lblNome;
    private javax.swing.JLabel _lblPosicao;
    private javax.swing.JButton btnCarregarDigital;
    private javax.swing.JButton btnCarregarFoto;
    private javax.swing.JButton btnCriar;
    private javax.swing.JComboBox<String> cbPosicao;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDigital;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JPanel pnDigital;
    private javax.swing.JPanel pnFoto;
    private javax.swing.JSpinner spID;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
