/*
 * Copyright 2017 BarelyAliveMau5.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ui;

import gerenciador.Perfil;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class frmPerfil extends javax.swing.JFrame {

    // usado pra voltar na janela anterior.
    private final javax.swing.JFrame parent;
    private final Perfil perfil;
    
    /**
     * Creates new form frmIdentificacao
     * @param parent janela pai
     * @param perfil perfil a carregar
     */
    public frmPerfil(javax.swing.JFrame parent, Perfil perfil) {
        initComponents();
        this.parent = parent;
        this.perfil = perfil;
        this.setLocationRelativeTo(null);  // centralizar janela
        if (perfil.getImagem_perfil() == null)
            lblPerfil.setIcon(new ImageIcon(ClassLoader.getSystemResource("res/no_profile.png")));
        else
            lblPerfil.setIcon(new ImageIcon(
                    new ImageIcon(perfil.getImagem_perfil())
                            .getImage()
                            .getScaledInstance(lblPerfil.getWidth(), 
                                               lblPerfil.getHeight(), 
                                               Image.SCALE_DEFAULT)));
        lblID.setText(String.valueOf(perfil.getID()));
        lblNome.setText(perfil.getNome());
        lblPosicao.setText(perfil.getPosicao().toString());
        switch (perfil.getPosicao()){
            case ministro_do_meio_ambiente:
                cbInfoSigilosas.setSelected(true);
                cbInfoRestritas.setSelected(true);
                cbInfoBasicas.setSelected(true);
                sldNivelAcesso.setValue(3);
                break;
            case diretor:
                cbInfoRestritas.setSelected(true);
                cbInfoBasicas.setSelected(true);
                sldNivelAcesso.setValue(2);
                break;
            case funcionario: 
                cbInfoBasicas.setSelected(true);
                sldNivelAcesso.setValue(1);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPerfil = new javax.swing.JPanel();
        lblPerfil = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNome_ = new javax.swing.JLabel();
        lblID_ = new javax.swing.JLabel();
        lblPosicao_ = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblPosicao = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        lblNivelAcesso_ = new javax.swing.JLabel();
        sldNivelAcesso = new javax.swing.JSlider();
        lblPermissoes_ = new javax.swing.JLabel();
        cbInfoBasicas = new javax.swing.JCheckBox();
        cbInfoRestritas = new javax.swing.JCheckBox();
        cbInfoSigilosas = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biometrica - Perfil");
        setLocationByPlatform(true);

        pnPerfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnPerfil.setLayout(new java.awt.BorderLayout());
        pnPerfil.add(lblPerfil, java.awt.BorderLayout.CENTER);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setText("Perfil de acesso");

        lblNome_.setText("Nome:");

        lblID_.setText("ID:");

        lblPosicao_.setText("Posição:");

        lblNome.setText("-");
        lblNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblID.setText("-");
        lblID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblID.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblPosicao.setText("-");
        lblPosicao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPosicao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblNivelAcesso_.setText("Nivel de acesso:");

        sldNivelAcesso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sldNivelAcesso.setMajorTickSpacing(1);
        sldNivelAcesso.setMaximum(3);
        sldNivelAcesso.setMinimum(1);
        sldNivelAcesso.setPaintLabels(true);
        sldNivelAcesso.setPaintTicks(true);
        sldNivelAcesso.setSnapToTicks(true);
        sldNivelAcesso.setEnabled(false);

        lblPermissoes_.setText("Permissões:");

        cbInfoBasicas.setText("Acessar informações básicas");
        cbInfoBasicas.setEnabled(false);

        cbInfoRestritas.setText("Acessar informações restritas");
        cbInfoRestritas.setEnabled(false);

        cbInfoSigilosas.setText("Acessar informações sigilosas");
        cbInfoSigilosas.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPosicao_)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblID_)
                                    .addComponent(lblNome_))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNivelAcesso_)
                                    .addComponent(lblPermissoes_))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbInfoBasicas)
                                    .addComponent(sldNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbInfoRestritas)
                                    .addComponent(cbInfoSigilosas))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(pnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID_)
                            .addComponent(lblID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome_)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPosicao_)
                            .addComponent(lblPosicao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNivelAcesso_)
                            .addComponent(sldNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbInfoBasicas)
                    .addComponent(lblPermissoes_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbInfoRestritas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbInfoSigilosas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        if (parent != null)
            parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox cbInfoBasicas;
    private javax.swing.JCheckBox cbInfoRestritas;
    private javax.swing.JCheckBox cbInfoSigilosas;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID_;
    private javax.swing.JLabel lblNivelAcesso_;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome_;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblPermissoes_;
    private javax.swing.JLabel lblPosicao;
    private javax.swing.JLabel lblPosicao_;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnPerfil;
    private javax.swing.JSlider sldNivelAcesso;
    // End of variables declaration//GEN-END:variables
}
